image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build_job:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker logout

test_job:
  image: $CONTAINER_TEST_IMAGE
  stage: test
  script:
    - chmod -R a+x node_modules
    - npm run test

  artifacts:
    when: always
    paths:
      - /builds/unbox_robotics/sort-system/cbs/test-suite/dashboard-ui-smoke-test-suite/test/reports/
